### ISSUE TITLE
Make NR type-aware

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/NameResolution#32]
When the UI is calling name-resolution, it frequently knows what type it wants.  Right now there is no ability to filter by type, so even if you know you want chemicals, you might get back a bunch of diseases.   Not only that, but NR doesn't even have the data to return for filtering, we make people go to NN to get the types.

Somehow we should probably bring type info into this.  I wonder if really all of NR should merge with NN in general...

@gaurav do you have any thoughts here?

See https://github.com/NCATSTranslator/Feedback/issues/42

**Comment by gaurav** [comment]
No immediate thoughts, but adding just the Biolink type to Babel synonyms should be pretty straightforward:
- Add biolink type to synonyms files.
- Import biolink type into Apache Solr index.
- Include biolink type in NameRes API.

I _don't_ like the idea of merging NR+NN just yet, but that might just be because I don't know enough about doing text indexing in Redis to know if we could do everything there :). I think they're sufficiently different that maintaining them as different projects makes sense.
