### ISSUE TITLE
Query for "HIV" fails...

### ISSUE THREAD

**Issue by GitHubbit** [TranslatorSRI/NameResolution#55]
```
`nr_url = 'https://name-resolution-sri.renci.org/lookup'
params = {'string':"HIV", 'limit':-1}
r = requests.post(nr_url, params=params)
print(r.json())`
```

I get a "JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
I try other names for HIV. "human immunodeficiency virus" gives the same error, but "HIV/AIDS" returns CURIEs.

-Kamileh from Multiomics

**Comment by gaurav** [comment]
I think the problem is in the `limit` parameter -- I don't think we intend to support `-1` as a valid limit, but we use it as a [facet limit](https://solr.apache.org/guide/6_6/faceting.html#Faceting-Thefacet.limitParameter), which seems to hit some kind of limit with our current Solr queries. I think this causes this query to fail where the number of results hit some internal limit; this works correctly with "HIV/AIDS" since that matches far fewer synonyms than either "HIV" or "human immunodeficiency virus". But both of those queries work with non-negative limits, up to our maximum (1000).

Do you really need to be able to return all synonyms? If so, we're currently planning to remove that functionality in PR #46, which will no longer allow negative limits, so we should make sure we can still support your use-case!

I tried to work around this by changing the `offset` parameter, but I ran into an error message when I tried to do that. So I'll fix that before I close this issue. Thank you for reporting it!

- [ ] Fix error caused by increasing offset values.

**Comment by GitHubbit** [comment]
I used this when Clinical KPs (ICEES, COHD, and EHR Risk) were attempting to determine how much overlap we had amongst us 3 providers given the test case of: What drugs treat asthma? To maximize overlap, we returned all possible synonyms. That certainly helped improve overlap, and further begs the question: should Clinical Evidence be stronger when Clinical KPs agree on an edge, and how might this be used by O&O? That maaaay be a future consideration. In short, at present, we do not need this, but I wanted to provide context in case it pops up again in the future :) Thank you for the response and help, and I went ahead and set the non-negative maximum I needed for this particular case.  
-Kamileh from Multiomics
