### ISSUE TITLE
403 Forbidden error with certain search strings in new Name Resolver

### ISSUE THREAD

**Issue by CaseyTa** [TranslatorSRI/NameResolution#84]
With some search strings, the new name resolver (http://name-resolution-sri-dev.apps.renci.org/docs#/lookup/lookup_curies_get_lookup_get) returns 403 Forbidden error.

Strings where 403 is returned:
```
influenza virus vaccine, inactivated A-Victoria-210-2009 X-187 (H3N2) (A-Perth-16-2009) strain
influenza virus vaccine, inactivated a-uruguay-716-2007 (h3n2) (a-brisbane-10-2007-like) strain
influenza virus vaccine, inactivated a-victoria-210-2009 x-187 (h3n2) (a-perth-16-2009) strain
```

Deleting the `(H3N2)` seems to get it to return, e.g., 
`influenza virus vaccine, inactivated A-Victoria-210-2009 X-187 (A-Perth-16-2009) strain`. 

But oddly, putting `(H3N2)` back in a different place doesn't trigger the 403, e.g., 
`influenza virus vaccine, inactivated A-Victoria-210-2009 X-187 (A-Perth-16-2009) strain (H3N2)`

**Comment by gaurav** [comment]
This was because of a security filter at RENCI. We've now removed the filter from https://name-resolution-sri.renci.org/docs and it shouldn't apply to https://name-lookup.ci.transltr.io/docs. I've tested all three queries on both those endpoints without a 403 error, so I think we can close this now. But please reopen this if this error is still ongoing somewhere that I haven't noticed!
